# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "This lane builds Debug Apk"
        lane :buildDebugApk do
             gradle(
            task: "clean assemble",
            flavor: "dev",
            build_type: "Debug"
        )
        end
 	desc "This lane builds the Dev release APK and Distribute to Internal testers via Firebase"
        lane :buildReleaseDevTestAPk do
            gradle(
      		task: "clean assemble",
      		flavor: "dev",
     		build_type: "Release"
    	)
    	end

    desc "Run unit tests for all variants"
         lane :test do
        gradle(task: "test")
      end

   desc "Generate Jacoco coverage reports on the DevDebug build"
    lane :testCoverage do
      gradle(task: "testDevDebugUnitTestCoverage")
    end


  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
